title: bouveng
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.82116
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#E6E7BB'
    - '#8B8177'
    - '#7B645C'
    - '#170201'
    - '#A09E98'
  lightness: 0.1960257
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: bouveng
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5870032
layout_spectrum: 1
