name: bouveng
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.49337
title: bouveng
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddddd'
    - '#acacac'
    - '#0d0d0d'
    - '#6d6d6d'
    - '#3b3b3b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 7bbf09a9-89e7-4027-8faa-884c2f620679
    url: null
